version: "3.6"

services:
    verdaccio:
        image: verdaccio/verdaccio:4
        container_name: verdaccio
        ports:
            - 4873:4873
        volumes:
            - ./conf:/verdaccio/conf

    nginx:
        build: .
        restart: always
        ports:
            - 80:80
