version: "3.6"

services:
    verdaccio:
        build: .
        container_name: verdaccio
        ports:
            - 4873:4873
        volumes:
            - ./conf:/verdaccio/conf
            - ./storage:/verdaccio/storage
            - ./plugins:/verdaccio/plugins

    nginx:
        build: ./nginx
        restart: always
        ports:
            - 80:80
